### ISSUE TITLE
No answer

### ISSUE THREAD

**Issue by GIDLak** [Kiruha01/bot_callback#9]
Не понял, почему пишет **"No answer"**, в чем проблема . С некоторыми другими тестами работает.
Еще интересно программа ищет ответы до победного или есть встроенные ограничения?
![image](https://user-images.githubusercontent.com/73779184/159016637-9dac2cbc-ab4e-4f2a-b65a-71230ba21d4d.png)

**Comment by Kiruha01** [comment]
**Проблема решена.** 
Для генерации тестов ЕГЭ использовался неподходящий параметр `scenario`. Теперь этот параметр берётся из самого теста, ответы на который необходимо найти.

**Comment by Kiruha01** [comment]
По поводу ограничений: по умолчанию создаются 20 тестов, содержащих 36 вопросов различной сложности. 
Количество тестов можно увеличить, поменяв значение переменной 
https://github.com/Kiruha01/examer/blob/d2edbd8782c327f335fa7e299b0e608793366999/examer.py#L96
